app/urls.py
from django.urls import path
from app import views


app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path(
        "<int:day>/<int:month>/<int:year>/<slug:slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:id>/comment/", views.post_comment, name="post_comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("app.urls")),
]

app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.db.models import QuerySet
from taggit.managers import TaggableManager


# Create your models here.


class PostManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=175, unique_for_date="publish", blank=True)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )
    image = models.ImageField(upload_to="imagens/", null=True, blank=True)
    highlighted = models.BooleanField(default=False)
    objects = models.Manager()
    published = PostManager()
    tags = TaggableManager()

    @classmethod
    def get_latest_post(cls, num_post=3):
        return cls.objects.filter(status=cls.Status.PUBLISHED).order_by("-publish")[
            :num_post
        ]

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.day, self.publish.month, self.publish.year, self.slug],
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f" {self.title} por {self.author}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=200)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()
    content = models.TextField()

    def __str__(self):
        return f"Comentário de {self.name} em {self.post}"

app/forms.py
from django import forms
from app.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "content")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
        }

app/views.py
from django.shortcuts import render, get_object_or_404
from app.models import Post
from app.forms import CommentForm
from django.views.decorators.http import require_POST

# Create your views here.


# listar todos os posts
def post_list(request):
    posts = Post.published.all()
    latest_posts = Post.get_latest_post(3)
    context = {
        "posts": posts,
        "latest_posts": latest_posts,
    }
    return render(request, "post_list.html", context)


# listar um post específico
def post_detail(request, day, month, year, slug):
    post = get_object_or_404(
        Post, publish__day=day, publish__month=month, publish__year=year, slug=slug
    )
    latest_posts = Post.get_latest_post(3)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        "post": post,
        "latest_posts": latest_posts,
        "comments": comments,
        "form": form,
    }
    return render(request, "post_detail.html", context)


@require_POST
def post_comment(request, id):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, id=id)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    else:
        comment = None
    context = {
        "post": post,
        "comment": comment,
        "form": form,
    }
    return render(request, "comment_success.html", context)

app/templates/comment_form.html
{% load bootstrap %}
<h2 class="mt-5">Adicionar comentário</h2>
<form class="col-md-8 mt-" action="{% url 'blog:post_comment' post.id %}" method="POST">
    {% csrf_token %}
    {{ form|bootstrap }}
    <p><input type="submit" class="btn btn-outline-dark mt-2" value="Add comentário"></p>
</form>

app/templates/comment_success.html
{% extends "base.html" %}
{% block title %}Adicionar comentário{% endblock %}
{% block content %}
{% if comment %}
<h2>Seu comentário foi adicionado</h2>
<p><a href="{{ post.get_absolute_url }}">Voltar para o post</a></p>
{% else %}
{% include "comment_form.html" %}
{% endif %}
{% endblock %}

app/templates/comments.html
{% block content %}
<div class="row d-flex justify-content-center">
    <div class="col-md-12 col-lg-12">
        <h4 class="mb-0">Posts mais recentes</h4>
        <p class="fw-light mb-4 pb-2">Últimos comentários</p>
        <div class="card">
            <div class="card-body p-4">
                {% for comment in comments %}
                <div class="comment mb-4 d-flex align-items-start col-md-12 ">
                    <img class="rounded-circle shadow-1-strong me-3"
                        src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(23).webp" alt="avatar" width="60"
                        height="60" />
                    <div>
                        <h6 class="fw-bold mb-1">{{ comment.name }}</h6>
                        <div class="d-flex align-items-center mb-3">
                            <p class="mb-0">
                                {{ comment.created_at }}
                                <span class="badge bg-primary">{{ comment.active }}</span>
                            </p>

                        </div>
                        <p class="fs-10 comment-content" style="word-wrap: break-word;">
                            {{ comment.content }}
                        </p>
                    </div>
                </div>
                <hr>
                {% empty %}
                <h1 class="fs-1">Não há comentários</h1>
                {% endfor %}
                {% include "comment_form.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/post_detail.html
{% extends 'base.html' %}


{% block content %}
<article>
    <!-- Post header-->
    <header class="mb-4">
        <!-- Post title-->
        <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
        <!-- Post meta content-->
        <div class="text-muted fst-italic mb-2">Publicado por {{ post.author }} em {{ post.publish }}</div>
        <!-- Post categories-->
        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
    </header>
    <!-- Preview image figure-->
    <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg"
            alt="..." /></figure>
    <!-- Post content-->
    <section class="mb-5">
        <div class="text-center fs-1">{{ post.title }}</div>
        <p class="fs-5 mb-4">{{ post.content }}</p>
    </section>
</article>
<div>
    {% include "comments.html" %}
</div>
{% endblock %}

app/templates/post_list.html
{% extends 'base.html' %}
{% block content %}
{% for post in posts %}
<div class="card mb-4">

    <a href="#!"><img class="card-img-top" src="https://dummyimage.com/900x350/dee2e6/6c757d.jpg" alt="..." /></a>
    <div class="card-body">
        <div class="small text-muted">{{ post.publish }} → {{ post.author }}</div>
        <h2 class="card-title">{{ post.title }}</h2>
        <p class="card-text">{{ post.content }}</p>
        <a class="btn btn-primary" href="{{ post.get_absolute_url }}">Read more →</a>
    </div>

</div>
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <title>{%block title %} Blog com Django {% endblock %}</title>
</head>

<body>

    {% include 'navbar.html' %}
    <div class="container mt-2 ">

        <div class="row">
            <div class="col-md-8 ">
                {% block content %}

                {% endblock %}
            </div>
            <div class="col-md-4">
                {% include 'sidebar.html' %}
            </div>

        </div>

</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">Django Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/posts.html
<div class="card mb-4">
    <a href="#!"><img class="card-img-top" src="https://dummyimage.com/900x350/dee2e6/6c757d.jpg" alt="..." /></a>
    <div class="card-body">
        <div class="small text-muted">January 1, 2023</div>
        <h2 class="card-title">Featured Post Title</h2>
        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
        <a class="btn btn-primary" href="#!">Read more →</a>
    </div>
</div>

templates/sidebar.html
<div class="col-md-10">
    <!-- Search widget-->
    <div class="card mb-4">
        <div class="card-header">Search</div>
        <div class="card-body">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Enter search term..."
                    aria-label="Enter search term..." aria-describedby="button-search" />
                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
            </div>
        </div>
    </div>
    <!-- Categories widget-->
    <div class="card mb-4">
        <div class="card-header text-center"><strong>Categorias</strong></div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-0">
                        <li><a href="#!">Web Design</a></li>
                        <li><a href="#!">HTML</a></li>
                        <li><a href="#!">Freebies</a></li>
                    </ul>
                </div>
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-0">
                        <li><a href="#!">JavaScript</a></li>
                        <li><a href="#!">CSS</a></li>
                        <li><a href="#!">Tutorials</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Side widget-->
    <div class="card mb-4">
        <div class="card-header text-center"><strong>Últimos Posts</strong></div>
        <ul class="list-unstyled mb-1">
            {% for last_post in latest_posts %}
            <li><a class="fs-5 text-center" style="text-decoration: none;" href="{{ last_post.get_absolute_url }}">
                    {{ last_post.title }}</a></li>
            {% endfor %}
        </ul>